#!/bin/bash

USERID=$(id -u)
TIMESTAMP=$(date +%F-%H-%M-%S)
SCRIPT_NAME=$(echo $0 | cut -d"." -f1)
LOGFILE=/tmp/$SCRIPT_NAME-$TIMESTAMP.log
R="\e[31m"
G="\e[32m"
N="\e[0m"
Y="\e[33m"

VALIDATE(){
 if [ $1 -ne 0]
 then 
     echo "$2...FAILURE"
     exit 1
 else
     echo "$2...SUCCESS"
 fi 
}


if [$USERID -ne 0 ]
then
    echo "Please run this script with root access." 
    exit 1 # manually exit if error comes.
else
    echo "you are super user."
fi 


dnf install mysql-server -y &>>$LOGFILE
VALIDATE $? "Installing MYSQL Server"

systemctl enable mysqld &>>$LOGFILE
VALIDATE $? "Enabling MYSQL Server"

systemctl start mysqld &>>$LOGFILE
VALIDATE $? "Starting MYSQL Server"

# mysql_secure_installation  --set--root-pass ExpenseApp@1 &>>$LOGFILE
# VALIDATE $? "setting up root password"

#Below code will be useful for idempotent nature
mysql -h db.daws78s.online -uroot -pExpenseApp@1 -e 'show databases;' &>>$LOGFILE
if [ $? -ne 0 ]
then 
    mysql_secure_installation --set--root-pass ExpenseApp@1 &>>$LOGFILE
    VALIDATE $? "MYSQL root password setup"
else
    echo "MYSQL Root password is already setup...$Y SKIPPING $N"
fi